name: Publish npm package

on:
  workflow_dispatch:
    inputs:
      package-version:
        description: 'Package version (e.g. 0.2.0)'
        required: true
        default: '0.1.32'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Install rollup platform binary
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Build npm package
        run: npm run build-npm

      - name: Set package version
        run: |
          cd custom_element_npm
          npm version ${{ github.event.inputs.package-version }} --no-git-tag-version

      - name: Publish to npm
        run: |
          cd custom_element_npm
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
